export type MovementPattern =
  | "push"
  | "pull"
  | "squat"
  | "hinge"
  | "lunge"
  | "core"
  | "conditioning"
  | "mobility";

export type Equipment = "none" | "pullup_bar" | "dumbbells" | "resistance_bands";

export type Difficulty = 1 | 2 | 3 | 4 | 5;

export type Exercise = {
  id: string;
  name: string;
  pattern: MovementPattern;
  difficulty: Difficulty;
  equipment: Equipment;
  /** Either reps or seconds. Reps for strength, seconds for isometric / conditioning. */
  unit: "reps" | "seconds";
  /** Default per-set dosage range as [easy, hard] used to scale by fitness level. */
  dosage: [number, number];
  description: string;
  cues?: string;
};

export const EXERCISES: Exercise[] = [
  // ---------- PUSH ----------
  {
    id: "wall_pushup",
    name: "Wall Push-Up",
    pattern: "push",
    difficulty: 1,
    equipment: "none",
    unit: "reps",
    dosage: [8, 15],
    description: "Stand arm's length from a wall, hands on wall at shoulder height, lower chest to wall and press back.",
    cues: "Keep body straight from head to heels; elbows ~45°.",
  },
  {
    id: "incline_pushup",
    name: "Incline Push-Up",
    pattern: "push",
    difficulty: 2,
    equipment: "none",
    unit: "reps",
    dosage: [8, 15],
    description: "Hands on a sturdy surface (couch, counter), body straight, lower chest to surface and push back.",
    cues: "Lower the surface = harder.",
  },
  {
    id: "knee_pushup",
    name: "Knee Push-Up",
    pattern: "push",
    difficulty: 2,
    equipment: "none",
    unit: "reps",
    dosage: [6, 12],
    description: "Push-up from the knees; straight line from head to knees.",
    cues: "Hips don't sag or pike.",
  },
  {
    id: "pushup",
    name: "Push-Up",
    pattern: "push",
    difficulty: 3,
    equipment: "none",
    unit: "reps",
    dosage: [6, 15],
    description: "Standard push-up, hands shoulder-width, body in a plank, lower chest to floor.",
    cues: "Squeeze glutes, brace core.",
  },
  {
    id: "wide_pushup",
    name: "Wide Push-Up",
    pattern: "push",
    difficulty: 3,
    equipment: "none",
    unit: "reps",
    dosage: [5, 12],
    description: "Push-up with hands wider than shoulders.",
  },
  {
    id: "diamond_pushup",
    name: "Diamond Push-Up",
    pattern: "push",
    difficulty: 4,
    equipment: "none",
    unit: "reps",
    dosage: [4, 10],
    description: "Push-up with thumbs and index fingers touching to form a diamond.",
    cues: "Elbows track close to ribs.",
  },
  {
    id: "pike_pushup",
    name: "Pike Push-Up",
    pattern: "push",
    difficulty: 4,
    equipment: "none",
    unit: "reps",
    dosage: [5, 10],
    description: "From a downward-dog position, lower head toward floor and press back up.",
    cues: "Hips high, weight forward over hands.",
  },

  // ---------- PULL ----------
  {
    id: "doorway_row",
    name: "Doorway Row",
    pattern: "pull",
    difficulty: 1,
    equipment: "none",
    unit: "reps",
    dosage: [8, 15],
    description: "Hold both sides of a sturdy doorframe, lean back with arms extended, then pull chest to frame.",
    cues: "Squeeze shoulder blades together.",
  },
  {
    id: "table_row",
    name: "Inverted Table Row",
    pattern: "pull",
    difficulty: 3,
    equipment: "none",
    unit: "reps",
    dosage: [5, 12],
    description: "Lie under a sturdy table, grip the edge, pull chest to table while keeping body straight.",
    cues: "Heels on floor, body rigid.",
  },
  {
    id: "towel_row",
    name: "Towel Row (Iso-Hold Pull)",
    pattern: "pull",
    difficulty: 2,
    equipment: "none",
    unit: "seconds",
    dosage: [20, 40],
    description: "Loop a towel around a sturdy post, lean back and hold a rowing position with elbows pulled.",
  },
  {
    id: "superman",
    name: "Superman Hold",
    pattern: "pull",
    difficulty: 2,
    equipment: "none",
    unit: "seconds",
    dosage: [15, 40],
    description: "Lie face-down, lift chest, arms, and legs off the floor and hold.",
    cues: "Squeeze glutes and upper back.",
  },
  {
    id: "y_t_w",
    name: "Floor Y-T-W Raises",
    pattern: "pull",
    difficulty: 2,
    equipment: "none",
    unit: "reps",
    dosage: [6, 10],
    description: "Lie face-down. Raise arms overhead in a Y, then out as a T, then bent as a W. That's 1 rep.",
  },
  {
    id: "pullup",
    name: "Pull-Up",
    pattern: "pull",
    difficulty: 5,
    equipment: "pullup_bar",
    unit: "reps",
    dosage: [3, 8],
    description: "Hang from a bar, pull chin over the bar.",
  },

  // ---------- SQUAT ----------
  {
    id: "chair_squat",
    name: "Chair Squat",
    pattern: "squat",
    difficulty: 1,
    equipment: "none",
    unit: "reps",
    dosage: [8, 15],
    description: "Sit back to a chair, tap glutes lightly, stand up.",
    cues: "Knees track over toes.",
  },
  {
    id: "bodyweight_squat",
    name: "Bodyweight Squat",
    pattern: "squat",
    difficulty: 2,
    equipment: "none",
    unit: "reps",
    dosage: [10, 20],
    description: "Feet shoulder-width, squat until thighs parallel, stand up.",
    cues: "Chest tall, weight in heels.",
  },
  {
    id: "sumo_squat",
    name: "Sumo Squat",
    pattern: "squat",
    difficulty: 2,
    equipment: "none",
    unit: "reps",
    dosage: [10, 18],
    description: "Wide stance, toes turned slightly out, squat down.",
  },
  {
    id: "jump_squat",
    name: "Jump Squat",
    pattern: "squat",
    difficulty: 4,
    equipment: "none",
    unit: "reps",
    dosage: [6, 12],
    description: "Squat then explode up into a jump, land softly into the next rep.",
  },
  {
    id: "bulgarian_split",
    name: "Bulgarian Split Squat",
    pattern: "squat",
    difficulty: 4,
    equipment: "none",
    unit: "reps",
    dosage: [6, 10],
    description: "Rear foot elevated on chair, front leg performs a squat. Reps each side.",
  },
  {
    id: "wall_sit",
    name: "Wall Sit",
    pattern: "squat",
    difficulty: 2,
    equipment: "none",
    unit: "seconds",
    dosage: [20, 60],
    description: "Back to wall, slide down until thighs are parallel, hold.",
  },

  // ---------- HINGE ----------
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    pattern: "hinge",
    difficulty: 1,
    equipment: "none",
    unit: "reps",
    dosage: [10, 20],
    description: "Lie on back, knees bent, drive hips up by squeezing glutes.",
  },
  {
    id: "single_leg_bridge",
    name: "Single-Leg Glute Bridge",
    pattern: "hinge",
    difficulty: 3,
    equipment: "none",
    unit: "reps",
    dosage: [6, 12],
    description: "Glute bridge with one leg extended. Reps each side.",
  },
  {
    id: "good_morning",
    name: "Bodyweight Good Morning",
    pattern: "hinge",
    difficulty: 2,
    equipment: "none",
    unit: "reps",
    dosage: [10, 15],
    description: "Hands behind head, hinge at hips with a soft knee, return to standing.",
    cues: "Flat back, push hips back.",
  },
  {
    id: "single_leg_deadlift",
    name: "Single-Leg RDL (Bodyweight)",
    pattern: "hinge",
    difficulty: 4,
    equipment: "none",
    unit: "reps",
    dosage: [6, 10],
    description: "Stand on one leg, hinge forward keeping back flat, return. Reps each side.",
  },

  // ---------- LUNGE ----------
  {
    id: "reverse_lunge",
    name: "Reverse Lunge",
    pattern: "lunge",
    difficulty: 2,
    equipment: "none",
    unit: "reps",
    dosage: [6, 12],
    description: "Step back into a lunge, return. Reps each side.",
  },
  {
    id: "forward_lunge",
    name: "Forward Lunge",
    pattern: "lunge",
    difficulty: 3,
    equipment: "none",
    unit: "reps",
    dosage: [6, 12],
    description: "Step forward into a lunge, return. Reps each side.",
  },
  {
    id: "lateral_lunge",
    name: "Lateral Lunge",
    pattern: "lunge",
    difficulty: 3,
    equipment: "none",
    unit: "reps",
    dosage: [6, 10],
    description: "Step out wide, sit hips back over that leg, return. Reps each side.",
  },
  {
    id: "step_up",
    name: "Step-Up",
    pattern: "lunge",
    difficulty: 2,
    equipment: "none",
    unit: "reps",
    dosage: [8, 12],
    description: "Step up onto a sturdy box/stair, drive through the heel. Reps each side.",
  },

  // ---------- CORE ----------
  {
    id: "plank",
    name: "Forearm Plank",
    pattern: "core",
    difficulty: 2,
    equipment: "none",
    unit: "seconds",
    dosage: [20, 60],
    description: "Forearms on floor, body straight from head to heels, hold.",
    cues: "Tuck pelvis, squeeze glutes.",
  },
  {
    id: "side_plank",
    name: "Side Plank",
    pattern: "core",
    difficulty: 3,
    equipment: "none",
    unit: "seconds",
    dosage: [15, 45],
    description: "On forearm, body straight on its side, hips lifted. Each side.",
  },
  {
    id: "dead_bug",
    name: "Dead Bug",
    pattern: "core",
    difficulty: 2,
    equipment: "none",
    unit: "reps",
    dosage: [8, 12],
    description: "On back, opposite arm + leg extend slowly, return, switch.",
    cues: "Lower back stays pressed to floor.",
  },
  {
    id: "bird_dog",
    name: "Bird Dog",
    pattern: "core",
    difficulty: 1,
    equipment: "none",
    unit: "reps",
    dosage: [8, 12],
    description: "On hands and knees, extend opposite arm and leg, return. Reps each side.",
  },
  {
    id: "leg_raises",
    name: "Lying Leg Raises",
    pattern: "core",
    difficulty: 3,
    equipment: "none",
    unit: "reps",
    dosage: [8, 15],
    description: "Lie flat, lift legs to ~90°, lower slowly without touching floor.",
  },
  {
    id: "hollow_hold",
    name: "Hollow Body Hold",
    pattern: "core",
    difficulty: 4,
    equipment: "none",
    unit: "seconds",
    dosage: [15, 40],
    description: "On back, lower back pressed down, legs and arms extended slightly off floor.",
  },
  {
    id: "bicycle_crunch",
    name: "Bicycle Crunches",
    pattern: "core",
    difficulty: 2,
    equipment: "none",
    unit: "reps",
    dosage: [10, 20],
    description: "On back, alternate elbow to opposite knee.",
  },

  // ---------- CONDITIONING ----------
  {
    id: "march_in_place",
    name: "March in Place",
    pattern: "conditioning",
    difficulty: 1,
    equipment: "none",
    unit: "seconds",
    dosage: [30, 60],
    description: "Lift knees, swing arms, easy pace.",
  },
  {
    id: "jumping_jacks",
    name: "Jumping Jacks",
    pattern: "conditioning",
    difficulty: 2,
    equipment: "none",
    unit: "seconds",
    dosage: [30, 60],
    description: "Classic jumping jacks.",
  },
  {
    id: "high_knees",
    name: "High Knees",
    pattern: "conditioning",
    difficulty: 3,
    equipment: "none",
    unit: "seconds",
    dosage: [20, 45],
    description: "Run in place, drive knees up to hip height.",
  },
  {
    id: "mountain_climbers",
    name: "Mountain Climbers",
    pattern: "conditioning",
    difficulty: 3,
    equipment: "none",
    unit: "seconds",
    dosage: [20, 45],
    description: "Plank position, drive knees alternately toward chest.",
  },
  {
    id: "burpee",
    name: "Burpee",
    pattern: "conditioning",
    difficulty: 5,
    equipment: "none",
    unit: "reps",
    dosage: [5, 12],
    description: "Squat, plank, (optional push-up), jump back, stand and hop.",
  },
  {
    id: "skater",
    name: "Skater Hops",
    pattern: "conditioning",
    difficulty: 3,
    equipment: "none",
    unit: "seconds",
    dosage: [20, 45],
    description: "Bound side to side landing on one leg at a time.",
  },

  // ---------- MOBILITY ----------
  {
    id: "cat_cow",
    name: "Cat-Cow",
    pattern: "mobility",
    difficulty: 1,
    equipment: "none",
    unit: "reps",
    dosage: [8, 12],
    description: "On hands and knees, alternate rounding and arching the spine.",
  },
  {
    id: "worlds_greatest",
    name: "World's Greatest Stretch",
    pattern: "mobility",
    difficulty: 2,
    equipment: "none",
    unit: "reps",
    dosage: [4, 6],
    description: "Lunge, hand inside front foot, rotate top arm to ceiling, switch sides.",
  },
  {
    id: "hip_flexor_stretch",
    name: "Half-Kneeling Hip Flexor Stretch",
    pattern: "mobility",
    difficulty: 1,
    equipment: "none",
    unit: "seconds",
    dosage: [30, 45],
    description: "Half kneel, squeeze glute of back leg, gentle stretch. Each side.",
  },
  {
    id: "hamstring_stretch",
    name: "Seated Hamstring Stretch",
    pattern: "mobility",
    difficulty: 1,
    equipment: "none",
    unit: "seconds",
    dosage: [30, 45],
    description: "Sit on the floor, one leg straight out, fold forward over the leg with a flat back.",
  },
  {
    id: "thoracic_rotation",
    name: "Thoracic Rotation (Open Book)",
    pattern: "mobility",
    difficulty: 1,
    equipment: "none",
    unit: "reps",
    dosage: [6, 10],
    description: "Side-lying, knees stacked, rotate top arm and shoulder open to the floor behind you.",
  },
  {
    id: "childs_pose",
    name: "Child's Pose",
    pattern: "mobility",
    difficulty: 1,
    equipment: "none",
    unit: "seconds",
    dosage: [30, 60],
    description: "Sit hips back to heels, arms extended forward, breathe.",
  },
  {
    id: "ankle_rocks",
    name: "Ankle Rocks",
    pattern: "mobility",
    difficulty: 1,
    equipment: "none",
    unit: "reps",
    dosage: [8, 12],
    description: "Half-kneel, drive front knee forward over toes without lifting heel.",
  },
];

export function byPattern(pattern: MovementPattern): Exercise[] {
  return EXERCISES.filter((e) => e.pattern === pattern);
}
